server:
  port: 8989
cas:
  server-url-prefix: http://sso.maxkey.top/sign/authz/cas/
  server-login-url: http://sso.maxkey.top/sign/authz/cas/login
  client-host-url: http://127.0.0.1:8989/
  validation-type: cas
#  拦截的URL地址
  authentication-url-patterns:
    - /test1/index
    - /test1/index1